version: "3.8"
services:
    backend1:
        build:
            context: ./backend-suzuki
        ports:
            - "4001:4000"     # Map to different ports to avoid conflicts
        networks:
            - backend-network
        environment:
            - DB_URL
            - DEVELOPMENT_DB_URL
            - PORT
            - SALT
            - SECRET
            - NODE_ENV
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - BUCKET_NAME
    backend2:
        build:
            context: ./backend-suzuki
        ports:
            - "4002:4000"     # Map to different ports
        networks:
            - backend-network
        environment:
            - DB_URL
            - DEVELOPMENT_DB_URL
            - PORT
            - SALT
            - SECRET
            - NODE_ENV
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - BUCKET_NAME

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        depends_on:
            - backend1
            - backend2
        networks:
            - backend-network

networks:
  backend-network: 
    driver: bridge
